[package]
name = "protov-core"
version = "0.1.0"
edition = "2024"
authors = ["Alex Xia <alex.xia@flakeblade.com>"]

[lib]

[dependencies]
heapless = "0.8"
micromath = "2.1.0"
embedded-graphics = { version = "0.8.1", default-features = false }
smart-leds = "0.4.0"

[dev-dependencies]
rstest = "0.23"

[features]
test-harness = []
hw-a0 = []
hw-a1 = []
hw-a2 = []

[[test]]
name = "integration"
required-features = ["test-harness"]
