[workspace]
members = ["protov-bootloader", "protov-core", "protov-hal", "protov-hal-mock", "protov-nvm", "protov-scpi"]
resolver = "2"

[workspace.package]
version = "1.7.2"
edition = "2024"
authors = ["Alex Xia <alex.xia@flakeblade.com>"]

[profile.release]
debug = 2
lto = true
opt-level = "z"

[profile.dev]
debug = 2
lto = true
opt-level = "z"
