[package]
name = "protov-hal"
version = "0.1.0"
edition = "2024"
authors = ["Alex Xia <alex.xia@flakeblade.com>"]

[[bin]]
name = "protov"
path = "src/main.rs"
test = false
bench = false

[lib]
path = "src/lib.rs"

[dependencies]
protov-core = { path = "../protov-core" }
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
embedded-storage = "0.3.1"
cortex-m-rt = "0.7.3"
embassy-embedded-hal = { version = "0.3.0", features = ["defmt"] }
embassy-executor = { version = "0.7", features = ["task-arena-size-16384", "arch-cortex-m", "executor-thread", "defmt", "executor-interrupt"] }
embassy-sync = { version = "0.6" }
embassy-time = { version = "0.4", features = ["defmt", "defmt-timestamp-uptime"] }
cortex-m = { version = "0.7.6" }
embassy-rp = { version = "0.4", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp2040"] }
embassy-usb = { version = "0.4", features = ["defmt"] }
portable-atomic = { version = "1.5", features = ["critical-section"] }
critical-section = "1.1"
display-interface-spi = "0.5.0"
embedded-graphics = "0.8.1"
mipidsi = "0.8.0"
display-interface = "0.5.0"
heapless = "0.8"
static_cell = "2.1.0"
u8g2-fonts = { version = "0.7.0", features = ["embedded_graphics_textstyle"] }
tinybmp = "0.6.0"
embedded-graphics-framebuf = "0.5.0"
micromath = "2.1.0"
smart-leds = "0.4.0"

[features]
default = ["calibrated"]
calibrated = []
demo = []
